const data = {
  products: [
    {
      _id: "1",
      name: "Dog Tag",
      category: "Basic",
      image: "/images/p1.jpg",
      price: 15,
      rating: 5,
      numReviews: 10,
      description: "A simple silver dog tag with a chain necklace.",
      countInStock: 10,
    },
    {
      _id: "2",
      name: "Weird Gold Pendant",
      category: "Basic",
      image: "/images/p2.jpg",
      price: 15,
      rating: 4,
      numReviews: 20,
      description: "A very weird gold pendant on a gold necklace.",
      countInStock: 15,
    },
    {
      _id: "3",
      name: "Black Ring",
      category: "Basic",
      image: "/images/p3.jpg",
      price: 15,
      rating: 4.5,
      numReviews: 15,
      description: "A small black chain necklace with gold studs.",
      countInStock: 7,
    },
    {
      _id: "4",
      name: "Ornate Pendant",
      category: "Basic",
      image: "/images/p4.jpg",
      price: 15,
      rating: 3,
      numReviews: 12,
      description: "A cool pendant with diamond and gold.",
      countInStock: 2,
    },
    {
      _id: "5",
      name: "Silver Heart",
      category: "Basic",
      image: "/images/p5.jpg",
      price: 12,
      rating: 5,
      numReviews: 18,
      description: "A simple silver necklace and heart pendant.",
      countInStock: 8,
    },
    {
      _id: "6",
      name: "Double Heart",
      category: "Basic",
      image: "/images/p6.jpg",
      price: 20,
      rating: 0.5,
      numReviews: 25,
      description:
        "A cute concentric heart pendant with a simple silver chain.",
      countInStock: 5,
    },
  ],
};

export default data;
